### ISSUE TITLE
ModuleNotFoundError: No module named 'interface'

### ISSUE THREAD

**Issue by xhl-xhl** [CatIIIIIIII/RNAErnie#4]
Hello！
When I run run_ssp.py，There is a error in secondary_structure.py【ModuleNotFoundError: No module named 'interface'】
Can you help me， thanks

**Comment by CatIIIIIIII** [comment]
The module interface is actually defined in the .so file [interface.cpython-38-x86_64-linux-gnu.so](https://github.com/CatIIIIIIII/RNAErnie/blob/main/interface.cpython-38-x86_64-linux-gnu.so). The file is compiled on linux and with python3.8. If you are running the code on a difference placeform or with a different version of python, you could compile this file from source at [mxfold2](https://github.com/mxfold/mxfold2).

**Comment by xhl-xhl** [comment]
thanks
