### ISSUE TITLE
add  rna_ernie.eval() in  Extract RNA Sequence Embeddings

### ISSUE THREAD

**Issue by duao42** [CatIIIIIIII/RNAErnie#6]
When Extract RNA Sequence Embeddings, need to set rna_ernie.eval(), otherwise the same input will have different outputs due to norm or dropout.

**Comment by CatIIIIIIII** [comment]
Thank you! Yes, you are right. This problem has been discussed #2, and the code in the test.py has been revised. And I found out just now the code in readme. Thank you again for you reminding.
