### ISSUE TITLE
Data preprocessing（rna_pretrainer.py）

### ISSUE THREAD

**Issue by xhl-xhl** [CatIIIIIIII/RNAErnie#7]
Hello，about create_masked_lm_predictions_motif function in rna_pretrainer.py. In 623 line，after new data append，don not np_rng.shuffle(ngram_indexes) again, is it a bug ？

**Comment by CatIIIIIIII** [comment]
Hi, it's not a bug. We prefer to use databased motifs rather than statistical motifs. So we do not shuffle here since we want to iterate the databased first.
