### ISSUE TITLE
if instance["input_ids"].shape[0] < 600:

### ISSUE THREAD

**Issue by jiosephlee** [CatIIIIIIII/RNAErnie#9]
In secondary_structure.py, there's line 1256 and line 1202 `if instance["input_ids"].shape[0] < 600:`

For secondary structure prediction, is the model only limited to sequences with < 600 base pairs?

**Comment by CatIIIIIIII** [comment]
No, the model itself could exceed 600 base pairs. However, we select only shorter sequences as the same with previsous work.
